server:
  port: 8080

spring:
  application:
    name: finance-tracing
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/finance}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: ${DB_POOL_SIZE:10}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: db/migrations
    schemas: public