version: '3'

services:

  postgres-db:
    image: postgres:12-alpine
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_MULTIPLE_DATABASES: "finance"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456

  finance-tracing:
    image: finance-tracing
    ports:
      - 8080:8080
    environment:
      DB_URL: "jdbc:postgresql://postgres-db:5432/finance"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "123456"